document.addEventListener('DOMContentLoaded', () => {
    // Select all necessary elements
    const videoUrlInput = document.getElementById('video-url');
    const fetchBtn = document.getElementById('fetch-btn');
    const videoInfoCard = document.getElementById('video-info-card');
    const videoTitle = document.getElementById('video-title');
    const videoThumbnail = document.getElementById('video-thumbnail');
    const statusMessage = document.getElementById('status-message');
    
    // --- SIMULATED DATA ---
    // A placeholder for the video information we would get from a backend API
    const simulatedVideoData = {
        title: "Introduction to Modern Web Design (HTML/CSS/JS)",
        thumbnailUrl: "https://via.placeholder.com/480x270/6366f1/FFFFFF?text=Awesome+Video+Thumbnail",
        formats: [
            { quality: "1080p", size: "150 MB" },
            { quality: "720p", size: "90 MB" },
            { quality: "MP3", size: "5 MB" }
        ]
    };

    // --- FUNCTIONALITY ---

    fetchBtn.addEventListener('click', () => {
        const url = videoUrlInput.value.trim();

        if (!url) {
            displayStatus('Please enter a valid video link.', 'error');
            return;
        }

        // 1. Start Loading State
        fetchBtn.classList.add('loading');
        videoInfoCard.classList.add('hidden');
        statusMessage.classList.add('hidden');
        
        // 2. Simulate API Call Delay (3 seconds)
        setTimeout(() => {
            
            // 3. End Loading State
            fetchBtn.classList.remove('loading');
            
            // For a real app, you'd handle network errors here.
            // For the demo, we always succeed.

            loadVideoInfo(simulatedVideoData);
            displayStatus('Video information fetched successfully!', 'success');

        }, 3000); // 3-second delay
    });

    // Function to populate the card with data
    function loadVideoInfo(data) {
        videoTitle.textContent = data.title;
        videoThumbnail.src = data.thumbnailUrl;
        
        // This makes the card visible
        videoInfoCard.classList.remove('hidden');
    }

    // Function to handle the Download buttons
    document.querySelectorAll('.download-btn').forEach(button => {
        button.addEventListener('click', (event) => {
            const formatOption = event.target.closest('.format-option');
            const quality = formatOption.getAttribute('data-quality');
            
            // SIMULATION of download start
            // The actual download link would be generated by your backend here.
            
            alert(`Simulating download for: ${quality} format. A real download would start now!`);
            
            // In a real scenario, you would redirect the user to the generated file URL
            // window.location.href = 'YOUR_BACKEND_GENERATED_DOWNLOAD_LINK';
        });
    });

    // Function to display status messages
    function displayStatus(message, type) {
        statusMessage.textContent = message;
        statusMessage.classList.remove('hidden', 'success', 'error');
        statusMessage.classList.add(type);
    }
});
